version: '3.9'
services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: psql_user
      POSTGRES_USER: adminlingkesh
      POSTGRES_PASSWORD: adminsecure1234
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresInitDB:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data