version: '3.9'
services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: psql_user
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: foo123
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./data/postgresInitDB:/docker-entrypoint-initdb.d:ro